LINK = '../Dataset/Weather_HCM_3.csv'
MODEL_RF = '../Model/RFv2.h5'
MODEL_RF_LSTM = '../Model/RF_LSTMv2.h5'
CERTIFICATE = '../Model/raspberry-esp32-firebase-adminsdk-dd5v3-8b0d728a1f.json'
DATABASE_URL = 'https://raspberry-esp32-default-rtdb.asia-southeast1.firebasedatabase.app'
